apiVersion: apps/v1
kind: Deployment
metadata:
  name: emesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emesh
  template:
    metadata:
      labels:
        app: emesh
    spec:
      containers:
      - name: emesh
        image: eventmesh/eventmesh:v1.4.0
        ports:
        - containerPort: 10000
        - containerPort: 10105
        volumeMounts:
        - name: emesh-props
          mountPath: /data/app/eventmesh/conf/eventmesh.properties
        - name: rmq-props
          mountPath: /data/app/eventmesh/conf/rocketmq-client.properties
      volumes:
      - name: emesh-props
        hostPath: 
          path: /data/eventmesh/rocketmq/conf/eventmesh.properties
          type: File
      - name: rmq-props
        hostPath: 
          path: /data/eventmesh/rocketmq/conf/rocketmq-client.properties
          type: File
