apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq-namesrv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmq-namesrv
  template:
    metadata:
      labels:
        app: rmq-namesrv
    spec:
      containers:
      - name: rmqnamesrv
        image: apache/rocketmq:4.9.4
        command: ["sh", "mqnamesrv"]
        ports:
        - containerPort: 9876
        volumeMounts:
        - name: namesrv-logs
          mountPath: /root/logs
        - name: namesrv-store
          mountPath: /root/store
      volumes:
      - name: namesrv-logs
        hostPath:
          path: /home/leodom/data/namesrv/logs
      - name: namesrv-store
        hostPath:
          path: /home/leodom/data/namesrv/store