apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmq
  template:
    metadata:
      labels:
        app: rmq
    spec:
      containers:
      - name: namesrv
        image: rocketmqinc/rocketmq-namesrv:4.5.0-alpine
        ports:
        - containerPort: 9876
        volumeMounts:
        - name: namesrv-logs
          mountPath: /root/logs
        - name: namesrv-store
          mountPath: /root/store
      - name: broker
        image: rocketmqinc/rocketmq-broker:4.5.0-alpine
        ports:
        - containerPort: 10911
        - containerPort: 10909
        volumeMounts:
        - name: broker-logs
          mountPath: /root/logs
        - name: broker-store
          mountPath: /root/store
        env:
        - name: NAMESRV_ADDR
          value: namesrv:9876
      volumes:
      - name: namesrv-logs
        hostPath:
          path: /home/leodom/data/namesrv/logs
      - name: namesrv-store
        hostPath:
          path: /home/leodom/data/namesrv/store
      - name: broker-logs
        hostPath:
          path: /home/leodom/data/broker/logs
      - name: broker-store
        hostPath:
          path: /home/leodom/data/broker/store