apiVersion: v1
kind: Service
metadata:
  name: kafka-test-consumer
spec:
  ports:
  - name: "toport3000"
    port: 3000
    targetPort: 3000
  - name: "toport80"
    port: 80
    targetPort: 80
  selector:
    app: kafka-test-consumer-app
  type: ClusterIP