apiVersion: v1
kind: Service
metadata:
  name: dummy-node-service
spec:
  selector:
    app: dummy-node-app
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: tcp
    protocol: TCP
    port: 80
    targetPort: 80